
benchmarks:
    -
        API: "mpi"
        filePerProcess: false
        processorGrid: [10,1,1]
        shape: [1000,1000,1000]
        paths: ["data"]
        isCollective: true
        repeat: 5